# Generated by Django 5.0.4 on 2024-04-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelApp', '0001_initial'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flightClassModel',
            fields=[
                ('flightClass_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('flightClass_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightClass_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightClass_is_active', models.BooleanField(default=True)),
                ('flightClass_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flightClass_tb',
            },
        ),
        migrations.CreateModel(
            name='flightModel',
            fields=[
                ('flight_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('flight_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightstay_icon', models.ImageField(upload_to='flight/')),
                ('flight_is_active', models.BooleanField(default=True)),
                ('flight_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flight_tb',
            },
        ),
        migrations.CreateModel(
            name='flightFacilitiesModel',
            fields=[
                ('flightFacilities_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('flightFacilities_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightFacilities_description', models.TextField(blank=True, default=None, null=True)),
                ('flightFacilities_is_active', models.BooleanField(default=True)),
                ('flightFacilities_created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightmodel')),
            ],
            options={
                'db_table': 'flightFacilities_tb',
            },
        ),
        migrations.CreateModel(
            name='flightDetailsModel',
            fields=[
                ('flightDetails_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('flightDetails_status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_departure_place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_destination_place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_departure_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_destination_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_timeperiod', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_departure_place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_destination_place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_departure_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_destination_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_timeperiod', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_discount', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_return_date', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('flightDetails_is_active', models.BooleanField(default=True)),
                ('flightDetails_created_at', models.DateTimeField(auto_now_add=True)),
                ('flightClass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightclassmodel')),
                ('flightFacilities', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightfacilitiesmodel')),
                ('flight', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightmodel')),
            ],
            options={
                'db_table': 'flightDetails_tb',
            },
        ),
        migrations.AddField(
            model_name='flightclassmodel',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightmodel'),
        ),
        migrations.CreateModel(
            name='userFlightBookModel',
            fields=[
                ('userFlightBook_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('userFlightBook_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userFlightBook_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userFlightBook_is_active', models.BooleanField(default=True)),
                ('userFlightBook_created_at', models.DateTimeField(auto_now_add=True)),
                ('flightDetails', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightmodel')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.signupmodel')),
                ('userGuest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.userguestmodel')),
            ],
            options={
                'db_table': 'userFlightBook_tb',
            },
        ),
    ]
