# Generated by Django 5.0.4 on 2024-04-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightmodel',
            old_name='flightstay_icon',
            new_name='flight_icon',
        ),
        migrations.RemoveField(
            model_name='flightclassmodel',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='flightdetailsmodel',
            name='flightClass',
        ),
        migrations.RemoveField(
            model_name='flightdetailsmodel',
            name='flightFacilities',
        ),
        migrations.RemoveField(
            model_name='flightfacilitiesmodel',
            name='flight',
        ),
        migrations.AddField(
            model_name='flightclassmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
        migrations.AddField(
            model_name='flightfacilitiesmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='userflightbookmodel',
            name='flightDetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flightApp.flightdetailsmodel'),
        ),
    ]
