# Generated by Django 5.0.4 on 2024-04-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('Billing_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('Billing_user', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Billing_destination', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Billing_flight', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Billing_hotel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Billing_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Billing_tb',
            },
        ),
        migrations.CreateModel(
            name='bookingSuccessfulModel',
            fields=[
                ('bookingSuccessful_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('bookingSuccessful_firstname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_lastname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_order_invoice', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_total_amount', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_payment_mode', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_phoneno', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_account_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bookingSuccessful_is_active', models.BooleanField(default=True)),
                ('bookingSuccessful_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.signupmodel')),
            ],
            options={
                'db_table': 'bookingSuccessful_tb',
            },
        ),
        migrations.CreateModel(
            name='userBillingModel',
            fields=[
                ('userBilling_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('userBilling_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_poastal_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_phoneno', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userBilling_is_active', models.BooleanField(default=True)),
                ('userBilling_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.signupmodel')),
            ],
            options={
                'db_table': 'userBilling_tb',
            },
        ),
    ]
