# Generated by Django 5.0.4 on 2024-04-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('Destination_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('Destination_place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Destinationstay_image', models.ImageField(upload_to='destination/')),
                ('Destination_is_active', models.BooleanField(default=True)),
                ('Destination_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Destination_tb',
            },
        ),
        migrations.CreateModel(
            name='DestinationstayModel',
            fields=[
                ('Destinationstay_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('Destinationstay_place_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Destinationstay_highligh_1', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_highligh_2', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_highligh_3', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_highligh_4', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_highligh_5', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_highligh_6', models.TextField(blank=True, default=None, null=True)),
                ('Destinationstay_meal_plan', models.BooleanField(default=True)),
                ('Destinationstay_services', models.BooleanField(default=True)),
                ('Destinationstay_inter_city_transfer', models.BooleanField(default=False)),
                ('Destinationstay_charges', models.BooleanField(default=True)),
                ('Destinationstay_lunch', models.BooleanField(default=True)),
                ('Destinationstay_parking_fees', models.BooleanField(default=False)),
                ('Destinationstay_breakfast', models.BooleanField(default=True)),
                ('Destinationstay_stationorairpot_pickanddrop', models.BooleanField(default=False)),
                ('Destinationstay_personal_travel', models.BooleanField(default=False)),
                ('Destinationstay_dinner', models.BooleanField(default=True)),
                ('Destinationstay_price', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Destinationstay_image_1', models.ImageField(upload_to='destination/')),
                ('Destinationstay_image_2', models.ImageField(upload_to='destination/')),
                ('Destinationstay_image_3', models.ImageField(upload_to='destination/')),
                ('Destinationstay_is_active', models.BooleanField(default=True)),
                ('Destinationstay_created_at', models.DateTimeField(auto_now_add=True)),
                ('Destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tourApp.destinationmodel')),
            ],
            options={
                'db_table': 'Destinationstay_tb',
            },
        ),
        migrations.CreateModel(
            name='UserselectdestinationModel',
            fields=[
                ('Userselectdestination_id', models.CharField(default=None, max_length=60, primary_key=True, serialize=False)),
                ('Userselectdestination_stay_period', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Userselectdestination_is_active', models.BooleanField(default=True)),
                ('Userselectdestination_created_at', models.DateTimeField(auto_now_add=True)),
                ('Destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tourApp.destinationmodel')),
            ],
            options={
                'db_table': 'Userselectdestination_tb',
            },
        ),
    ]
