# Generated by Django 5.0.4 on 2024-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationstaymodel',
            name='Destinationstay_image_4',
            field=models.ImageField(default=None, upload_to='destination/'),
        ),
        migrations.AddField(
            model_name='destinationstaymodel',
            name='Destinationstay_image_5',
            field=models.ImageField(default=None, upload_to='destination/'),
        ),
    ]
